//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONG.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class amislEntities : DbContext
    {
        public amislEntities()
            : base("name=amislEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ctacontable> ctacontable { get; set; }
        public virtual DbSet<estadistica> estadistica { get; set; }
        public virtual DbSet<etiqueta> etiqueta { get; set; }
        public virtual DbSet<gasto> gasto { get; set; }
        public virtual DbSet<gasto_rep> gasto_rep { get; set; }
        public virtual DbSet<idioma> idioma { get; set; }
        public virtual DbSet<ingreso> ingreso { get; set; }
        public virtual DbSet<ingreso_rep> ingreso_rep { get; set; }
        public virtual DbSet<nivel> nivel { get; set; }
        public virtual DbSet<nivel_usuario> nivel_usuario { get; set; }
        public virtual DbSet<rep_estadistica> rep_estadistica { get; set; }
        public virtual DbSet<rep_financiero> rep_financiero { get; set; }
        public virtual DbSet<tipo> tipo { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
    }
}
