//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class etiqueta
    {
        public string UUID { get; set; }
        public string VALOR { get; set; }
        public string UUID_IDIOMA { get; set; }
        public string UUID_REGISTRO { get; set; }
        public string IDENTIFICADOR { get; set; }
    
        public virtual idioma idioma { get; set; }
    }
}
