//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gasto
    {
        public string UUID { get; set; }
        public string IDENTIFICADOR { get; set; }
        public string UUID_CTACONTABLE { get; set; }
        public string UUID_TIPO { get; set; }
        public string NIVEL { get; set; }
    
        public virtual ctacontable ctacontable { get; set; }
        public virtual tipo tipo { get; set; }
    }
}
