//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ingreso_rep
    {
        public string UUID { get; set; }
        public decimal MONTO { get; set; }
        public string UUID_INGRESO { get; set; }
        public string UUID_REP_FINANCIERO { get; set; }
    }
}
