//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class nivel
    {
        public nivel()
        {
            this.nivel_usuario = new HashSet<nivel_usuario>();
        }
    
        public string UUID { get; set; }
        public string NIVEL1 { get; set; }
        public string IDENTIFICADOR { get; set; }
        public string SUPERIOR { get; set; }
    
        public virtual ICollection<nivel_usuario> nivel_usuario { get; set; }
    }
}
