//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rep_financiero
    {
        public string UUID { get; set; }
        public Nullable<int> MES { get; set; }
        public Nullable<int> ANIO { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public Nullable<decimal> SALDOANTERIOR { get; set; }
        public Nullable<decimal> TASACAMBIO { get; set; }
        public string NIVEL { get; set; }
    }
}
