//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public string UUID { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIDOS { get; set; }
        public string USUARIO1 { get; set; }
        public string TEL1 { get; set; }
        public string TEL2 { get; set; }
        public string TEL3 { get; set; }
        public string EMAIL { get; set; }
        public string DIR1 { get; set; }
        public string DIR2 { get; set; }
        public string DIR3 { get; set; }
        public string NIVEL { get; set; }
        public string CLAVE { get; set; }
    }
}
